---

- name: "Set fact {{ pod_network_plugin }} cni variable"
  set_fact:
    cni: "{{ vars[pod_network_plugin] }}"

- name: Create Kubernetes addon directory
  file: path={{ network_dir }} state=directory

- name: "Copy {{ cni.name }} yml file"
  become: yes
  template: src="{{ cni.template.ds }}.j2" dest={{ network_dir }}/{{ cni.template.ds }}

- name: "Check {{ cni.name }} daemonset is working"
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get ds --all-namespaces | grep {{ cni.name }}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_net
  ignore_errors: true

- name: "Create {{ cni.name }} network daemonset"
  when: check_net|failed
  shell: |
    kubectl create --kubeconfig={{ kubeadmin_config }} \
                   -f {{ network_dir }}/{{ cni.template.ds }}
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  run_once: true
