# The global variable file DDC installation
docker_package: docker-ce  #docker-ee, docker-ce, docker
docker_version: 18.03.1.ce # 17.06.2.ee.6, 17.06.2.ce

# overlay2(recommended for both ubuntu and centos) or devicemapper(centos/redhat. it must use direct-lvm mode), aufs(ubuntu)
# overlay2(keranl 4.0 or higher required but docker-ee can use with kernal 3.10-693 or above)
docker_storage_driver: overlay2 

# docker enterprise
# DDC license 
local_docker_ucp_subscription_file: "files/docker_subscription.lic"
docker_ucp_subscription_file: "/root/docker_subscription.lic"
docker_ucp_version: 3.0.0
docker_dtr_version: 2.5.0
docker_ucp_admin_username: admin
docker_ucp_admin_password: hpinvent

# ucp san(Subjective Alternative Name) - ip or URL 
# docker_ucp_san: ucp.docker.lan
docker_ucp_swarm_port: 2376
docker_ucp_controller_port: 443
docker_ucp_host_address: "{{ groups['docker_managers'][0] }}"
docker_ucp_controller_url: "https://{{ docker_ucp_host_address }}:{{ docker_ucp_controller_port }}"
docker_dtr_external_url: "{{ groups['docker_registries'][0] }}"
# ucp backup operation parameters
docker_ucp_backup_passfrase: ""
docker_ucp_backup_file: /tmp/ucp-backup.tar

proxy_env:
  dummy: dummy
  #http_proxy: http://web-proxy.kor.hp.com:8080
  #https_proxy: http://web-proxy.kor.hp.com:8080
