# The global variable file DDC installation
docker_package: docker-ce  #docker-ee, docker-ce, docker
docker_version: 17.06.2.ce # 17.06.2.ee.6, 17.06.2.ce

# overlay2(recommended for both ubuntu and centos) or devicemapper(centos/redhat. it must use direct-lvm mode), aufs(ubuntu)
# overlay2(keranl 4.0 or higher required but docker-ee can use with kernal 3.10-693 or above)
docker_storage_driver: overlay2 

# version for kubeadm, kubelet, kubectl
kube_version: v1.10.2
kube_token: xs417m.14zh364cyl4psodv

pod_network_plugin: calico #flannel


proxy_env:
  dummy: dummy
  #http_proxy: http://web-proxy.kor.hp.com:8080
  #https_proxy: http://web-proxy.kor.hp.com:8080

network_dir: /etc/kubernetes/network