---
kind: ConfigMap
apiVersion: v1
metadata:
  name: loginapp
  namespace: auth
data:
  config.yaml: |
    debug: false
    client_id: "loginapp"
    client_secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
    issuer_url: "https://dex.auth.svc.cluster.local:32000"
    issuer_root_ca: "/etc/ssl/ca.pem"
    redirect_url: "https://loginapp.atuh.svc.cluster.local:32002/callback"
    listen: "https://0.0.0.0:5555"
    tls_cert: "/etc/loginapp/tls/tls.crt"
    tls_key: "/etc/loginapp/tls/tls.key"
    disable_choices: false
    extra_scopes: "groups"
    app_name: "Kubernetes Auth"
