
---

- name: Copy UCP/DTR package files to first master node
  copy:
    src: "{{ item.src }}"
    dest: "/tmp/{{ item.dest }}"  
  with_items:
    - { src: docker_ucp_package_file, dest: docker_ucp_package_file }
    - { src: docker_dtr_package_file, dest: docker_dtr_package_file }


- name: Import UCP/DTR images 
  shell: docker load < /tmp/{{ item }}
  with_items:
    - docker_ucp_package_file
    - docker_dtr_package_file

