---

docker_ucp_version: 2.0.1
docker_dtr_version: 2.1.3
docker_ucp_admin_username: admin
docker_ucp_admin_password: hpinvent

#docker_ucp_version: "{{ docker_ucp_version if docker_ucp_version is not defined else  latest }}"
# offline UCP install
is_ucp_offline_install: no
docker_ucp_package_file: "ucp_dtr.tar.gz"
docker_dtr_package_file: "ucp_dtr.tar.gz"

# DDC license 
local_docker_ucp_subscription_file: "files/docker_subscription.lic"
docker_ucp_subscription_file: "/root/docker_subscription.lic"

docker_ucp_swarm_port: 2376
docker_ucp_controller_port: 443
docker_ucp_host_address: "{{ groups['docker_managers'][0] }}"
#docker_ucp_controller_url: "ucp.docker.lan"

docker_ucp_san:
  - ucp.docker.lan
docker_ucp_extra_args: ""
#docker_ucp_extra_args: "--disable-tracking --disable-usage --binpack"

docker_ucp_backup_passfrase: ""
docker_ucp_backup_file: /tmp/ucp-backup.tar
local_docker_ucp_backup_file: /tmp/ucp-backup.tar
docker_ucp_controller_url: "https://{{ docker_ucp_host_address }}:{{ docker_ucp_controller_port }}"