
---

- hosts: k8s_masters[0]
  tasks:
    - name: Fetch kubeconfig file from master
      become: yes
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        flat: yes
      

- name: "Install kubeadm"
  hosts: k8s_cli
  tasks:
    - name: Install kubectl 
      become: yes
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{kube_version}}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: 755

    - name: Create kubectl directory for non-root user 
      file: 
        path: ~/.kube
        state: directory

    - name: copy admin.conf to .kube directory
      copy:
        src: /tmp/admin.conf
        dest: "{{ansible_user_dir}}/.kube/config"

  environment: "{{ proxy_env }}"

