
---

- hosts: k8s_masters[0]
  tasks:
    - name: Fetch kubeconfig file from master
      become: yes
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "/tmp/admin.conf"
      

- name: "Install kubeadm"
  hosts: k8s_cli
  tasks:

    - name: Install kubectl 
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{kube_version}}/bin/linux/amd64/kubectl"
        dest: /usr/bin

    - name: Create kubectl directory for non-root user 
      file: 
        path: ~/.kube
        state: directory

    - set_fact:
        user_name: "{{ ansible_user_id }}"
        user_home: "{{ ansible_user_dir }}"
    
    - name: Fetch kubeconfig file from master
      copy:
        src: /tmp/admin.conf
        dest: "{{user_home}}/.kube/config"

  environment: "{{ proxy_env }}"

