
---

- name: "Install kubeadm"
  hosts: k8s_cli
  become: yes
  tasks:
    - name: Create kubectl directory for non-root user 
      file: 
        path: ~/.kube
        state: directory

    - set_fact:
        user_name: "{{ ansible_user_id }}"
        user_home: "{{ ansible_user_dir }}"
    
    - name: Fetch kubeconfig file from master
      become: yes
      synchronize:
        src: /etc/kubernetes/admin.conf
        dest: "{{user_home}}/.kube/config"
        set_remote_user: "{{user_name}}"
      delegate_to: "{{ groups['k8s_masters'][0]}}"

  environment: "{{ proxy_env }}"

