- name: "Install masters"
  hosts: k8s_masters
  roles:
    - role: kubeadm/bootstrap/master
   # - { role: cni, tags: cni }
  environment: "{{ proxy_env }}"


- name: "Install nodes"
  hosts: k8s_workers
  become: yes
  roles:
    - role: kubeadm/bootstrap/worker
  environment: "{{ proxy_env }}"
 