
- include: pkg-install-kubectl.yml

- name: "Install nodes"
  hosts: k8s_cli
  tasks:
    - name: Install helm 
      become: yes
      shell: "curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash"

    - name: Helm init -- create tiller account and init
      shell: |
        kubectl create serviceaccount --namespace kube-system tiller
        kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
        kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}
  environment: "{{ proxy_env }}"
 