--- 
- name: "Install portus docker registry"
  gather_facts: True
  hosts: all
  tasks:
    - name: Register Redhat subscription and attach automatically
      become: yes
      redhat_subscription:
        state: present
        username: "{{redhat_subscription_user}}"
        password: "{{redhat_subscription_pwd}}"
        autosubscribe: true
      when: redhat_subscription_user is defined and ansible_distribution == "RedHat"
  environment: "{{ proxy_env }}"
