--- 
- name: "Distribute docker/UCR certs and credentials"
  gather_facts: True
  hosts: dcos_cli[0]
  vars_files: 
    - pkg-desc/registry-portus.yml
  vars: 
    registry_package: portus
  roles:
    - { role: dcos/packages/registry/certs }
    - { role: dcos/packages/registry/credentials } 
  environment: "{{ proxy_env }}"
