--- 

- include: util-update-fact-cache.yml


- name: Install NFS server
  hosts: dcos_bootstrap
  gather_facts: no
  tags: ['nfs-server']
  roles:
    - { role: common/nfs, node_type: server }
  environment: "{{ proxy_env }}"


- name: Install NFS client
  hosts: dcos_bootstrap:dcos_slaves:dcos_slaves_public
  gather_facts: no
  tags: ['nfs-client']
  roles:
    - { role: common/nfs, node_type: client }
  environment: "{{ proxy_env }}"